name: BreakReminder
options:
  bundleIdPrefix: com.abhinav
  deploymentTarget:
    macOS: "13.0"
  createIntermediateGroups: true

settings:
  SWIFT_VERSION: "5.9"
  MACOSX_DEPLOYMENT_TARGET: "13.0"

targets:
  BreakReminder:
    type: application
    platform: macOS
    sources:
      - BreakReminder
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.abhinav.BreakReminder
      PRODUCT_NAME: BreakReminder
      INFOPLIST_FILE: BreakReminder/Info.plist
      MARKETING_VERSION: "1.0.0"
      CURRENT_PROJECT_VERSION: 1
      GENERATE_INFOPLIST_FILE: false
      CODE_SIGN_STYLE: Automatic
      ENABLE_HARDENED_RUNTIME: YES
      CODE_SIGN_IDENTITY: "-"
    entitlements:
      path: BreakReminder/BreakReminder.entitlements
      properties:
        com.apple.security.app-sandbox: false
